//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SignalR.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignalREntities : DbContext
    {
        public SignalREntities()
            : base("name=SignalREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblChatMessageDetail> tblChatMessageDetails { get; set; }
        public virtual DbSet<tblChatPrivateMessageDetail> tblChatPrivateMessageDetails { get; set; }
        public virtual DbSet<tblChatPrivateMessageMaster> tblChatPrivateMessageMasters { get; set; }
        public virtual DbSet<tblChatUserDetail> tblChatUserDetails { get; set; }
    }
}
